### PR TITLE
updated for Minecraft PE 0.10.4

### PR DESCRIPTION
**Pull request by ZCodeMT**

### CODE REVIEW

**Comment by jv110** [comment]
Where do you guys get those functions?

**Comment by byteandahalf** [comment]
@jv110 You need to decompile the Java side of MCPE

**Comment by jv110** [comment]
@byteandahalf Thanks!

**Comment by byteandahalf** [comment]
@jv110 You just use dex2jar to make the classes.dex into classes.jar, then use a java decompiler on the classes.

**Pull request merged**
